### ISSUE TITLE
Code suggestions close upon auto save

### ISSUE THREAD

**Issue by helzakar** [nmaxcom/brackets-autosaver#3]
While typing, code suggestions appear but because of the auto-saving they disappear as soon as the auto-save is triggered, rendering the suggestions feature impossible to use

Brackets version: Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
build timestamp: Wed Nov 02 2016 04:47:30 GMT-0700

Plugin version: 1.0.3

**Comment by nmaxcom** [comment]
Hey, thanks for the feedback. I'm not sure if there's a way of fixing this besides overhauling the extension and use a more "inconspicuous" saving system that doesn't interfere with issues like that one.

I'll give it some thought. What plugin is providing those code suggestions?

**Comment by helzakar** [comment]
Hi @nmaxcom

It's just the default Brackets suggestions like var names and such, no extra plugin as far as I know

**Comment by alexcooperdev** [comment]
Came here to report the same issue that @spectrumcat had. 

~~My suggestion would be that instead of saving every 400ms per keystroke, you make it so that each keystroke resets that timer back to 400ms without saving.~~ Edit: Sorry, I didn't realize that this is how it currently is. I guess I missed that part of the description.

I would also make the 400ms longer. Maybe like 5000ms (allow this to be edited by the user in preferences). This should give brackets and the user enough time to view and select a suggestion. 

~~Perhaps also include arrow keys in the keystroke auto-save reset timer, this way if a user is looking through the suggestions list the arrow key input will keep the auto-save from closing the list.~~ 
Edit: Another error on my end. Arrow keys aren't special. All keypresses are included.

Just an idea. Thanks for making this thing in the first place!

Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
build timestamp: Wed Nov 02 2016 04:47:30 GMT-0700
Plugin version: 1.0.4

Update: I tweaked the source code a bit and it seems to be working smoothly enough now. I made a new branch with the updated version if anyone wants to try it out.

**Comment by nmaxcom** [comment]
> My suggestion would be that instead of saving every 400ms per keystroke, you make it so that each keystroke resets that timer back to 400ms without saving.

Unless I misunderstood you, that's exactly how the extension works. Every keystroke clears the timer and sets it again so that whatever the last stroke is, it won't be cleared and will trigger that save.

> I would also make the 400ms longer. Maybe like 5000ms (allow this to be edited by the user in preferences). This should give brackets and the user enough time to view and select a suggestion.

Five seconds is way too much for the intended end user who is in the "edit and see changes" tight loop. This could be indeed left to tweak by the user.

> Perhaps also include arrow keys in the keystroke auto-save reset timer, this way if a user is looking through the suggestions list the arrow key input will keep the auto-save from closing the list.

I totally agree. I think I'll just go the other way and only react after alphanumerical and symbol inputs.

Let me poke with it and see what I can do. The Brackets API is really not that great, unfortunately.

**Comment by nmaxcom** [comment]
I found a way to check if any hinting window was open so now it seems that now work perfectly.

Let me know if it works

**Comment by nmaxcom** [comment]
I found a way to check if any hinting window was open so now it seems that now works perfectly at least in my machine: d924d65

Let me know if it works for you.

PS: I'm having a stupid battle with GitHub's comment system today :)

**Comment by alexcooperdev** [comment]
@nmaxcom Dude, you rock. I'm impressed by how quickly you were able to find out that you could detect if the code hints modal was open. I just installed the new version and it runs perfectly. Awesome job! 

Oh, and yeah, you're right. 5 seconds is way too long. I wasn't really thinking about it until I sat and counted 5 seconds out in my head. Haha. I lowered it to 2ish seconds in my fork, but your new version is perfect.

Thanks for addressing this so quickly. Enjoy the New Year this weekend!

**Comment by helzakar** [comment]
Awesome solution and works great now, thank you! Happy New Year! =)
