### ISSUE TITLE
Make save trigger interval configurable

### ISSUE THREAD

**Issue by jbmonroe** [nmaxcom/brackets-autosaver#4]
Too many write operations to an SSD reduces its useful life.  On a regular HDD I'm a fan of "twitch-saves" but on an SSD (and my current work machine is totally SSD) this has long-term consequences to the viability of the drive(s).  By allowing me to extend the trigger time I can maximize the usefulness of the plug-in without lowering the lifespan of my drives.

**Comment by nmaxcom** [comment]
I see where you are coming from. The original idea was to have these instant saves so that working with file watchers is a smooth process.

Having said that, we could think of something here. I assume you'd like to use the extension as the classical "save my work every 5 minutes in case something brakes" kind of thing?

**Comment by jbmonroe** [comment]
That wouldn't be bad (I might pick two minutes <g>).  Just being able to
kick it out to four seconds or 12 seconds after a keypress would be
good--it gives one time to think, then resume typing.  I wasn't clear on
which file watchers you were thinking of--WinLESS, maybe some sort of
TypeScript transpiler, automatic source-control submits?  I wouldn't want
them to auto-start on a half-finished thought.  (And I have a lot of those!)

Anything that keeps me from having to keep a command-line open to build
something after I've made an edit would be good--but an auto-save versus
catastrophes wasn't really what you were aiming for and I don't want to
take this off your original target.

**Comment by nmaxcom** [comment]
Since you are the first to ask, I'll leave this issue open for a while to see if more people would like to see that feature implemented.

In the meantime, it's very easy for you to modify your local copy of the extension and use the time you want, in milliseconds:

`var waitingPeriod = 400;`

> You can view this location using Help > Show Extensions Folder. Normally, this folder's contents are managed by Extension Manger.
> 
> Mac: ~/Library/Application Support/Brackets/extensions/user
> Win: C:\Users\<user>\AppData\Roaming\Brackets\extensions\user
> Linux: ~/.config/brackets/extensions/user

I hope this works.

**Comment by jbmonroe** [comment]
I'll do that on my home machine, which has both an HDD and SSD on it.  It looks promising.  Thanks!

**Comment by Lillecarl** [comment]
If there's an easy way to implement it in GUI i'd like to see the feature too, not high prio though =)

Thanks 👍

**Comment by nmaxcom** [comment]
Finally! Dialogs turned out to be nasty; I spent much more time than I thought I would.

I hope it's useful.
